apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - catalogsource.yaml

patches:
  - target:
      kind: Subscription
      name: rhods-operator
    path: patch-subscription.yaml
  - target:
      kind: OperatorGroup
      name: rhods-operator-group
    patch: |-
      - op: replace
        path: "/metadata/name"
        value: rhods-operator
