apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/auth-with-authorino
  - ../../components/components-distributed-compute
  - ../../components/components-kserve
  - ../../components/components-modelmesh
  - ../../components/components-training
  - ../../components/default-notebook-pvc-size
  - ../../components/dashboard-feature-hardware-profiles
  - ../../components/hardware-profiles-cpu
  - ../../components/idle-notebook-culling
  - ../../components/make-kubeadmin-cluster-admin
  - ../../components/rhoai-auth
